theme: jekyll-theme-minimal
title:Christophoros Palesis Poetry Homepage
description: This website will evolve as more and more of the Palesis poetry is published.  Please bookmark this page and come back soon to see what's new.
